### ISSUE TITLE
WRN: Assembly binding logging is turned off

### ISSUE THREAD

**Issue by xCausxn** [Da-Teach/Questor#115]
hi how do i fix this also questor will not start doing mission anbody now how to fix ? Thanks all help is appreciated.
http://forum.thehackerwithin.com/resource.ashx?i=53

**Comment by ISeeDEDPpl** [comment]
The problem is that you compiled with the "wrong" version of directeve.dll or do not have the same version that you compiled with in the .net programs directory with the questor.exe

Once you have a compiled with no errors version of questor.exe be sure to copy the same directeve.dll that you compiled with to the .net directory. If you cannot get it to work with the directeve.dll you are using, use the other version. There are 2 different versions the very compatible and longtime working well 3.5 version and the version that everyone tries to use but cant seem to figure out what they are doing 4.0 version.
