### ISSUE TITLE
[Feature Request] Align To (< % Shield or Armor)

### ISSUE THREAD

**Issue by Status12** [Da-Teach/Questor#26]
I would like to see this feature implemented into Questor if it is at all possible. Aligning to the nearest station when below a certain percentage (aligning prematurely will drastically improve warp time). It'll help get the ship out quicker. One issue is making sure the ship stays aligned and still.

**Comment by PoorNewb23** [comment]
Well, in lv4 you're either safe, or scrambled. Also, with a bit fo bad luck, it can be instant death sentence for speedtanking ships (what if your align point is in direct line to npcs? - Your tank is already getting pounded and you just reduced your transversal to 0).

Low priority feature. Would rather see "put" action implemented, so that Questor can finally do all the kill missions.

**Comment by Status12** [comment]
Well it would be a enable/disable feature if it were implemented, so speedtanking ships shouldnt have to worry. Quester takes priority of killing scramble/web ships too, so by the time your shield/armor is down, you shouldnt have to worry about the ships that web/scramble anyway.

**Comment by Status12** [comment]
Besides, after the recent patch I rarely, if at all get scrambled. I get webbed most of the time but that's nothing.

**Comment by rixim** [comment]
This feature seems more dangerous than useful, I would add it if there was a pull request, but I don't expect anyone to fill the request anytime soon...
