### ISSUE TITLE
Forgets to bring implants back from storylines

### ISSUE THREAD

**Issue by Blinker** [Da-Teach/Questor#31]
Sometimes Questor forgets to bring home implants done in storylines.

Any idea how to fix or get questor to double check?

**Comment by xelj** [comment]
If after materials for war preparation, tnen questor says that not enough cargo ("we are full")

**Comment by Blinker** [comment]
Mostly with war prep but also with the other implant storyline too.

Again, not always but sometimes

**Comment by Ganondorf0** [comment]
The issue is that an already open cargo will show as 0 capacity if not updated. So we need to either close the cargo of the shuttle (then reopen it) or add a simple hack if(cargo.Capacity==0) capacity=10;
That will fix it. It doesn't happen while mission running, because moving loot/ammo out of the cargo refreshes it. Seems to be a client/ccp related bug.

**Comment by rixim** [comment]
Ganondorf0, do I need to patch this?

**Comment by Ganondorf0** [comment]
No, with the latest patch questor needs to reopen the cargo anyway, so it should be solved by itself.
