### ISSUE TITLE
Turret not fitted on shipID

### ISSUE THREAD

**Issue by pfruh** [Da-Teach/Questor#48]
I don't know if this is normal, but im getting the following error on the LogServer while salvaging with my noctis
(using 3 salvagers and 5 tractor beams) everytime the console says "Salvage: Activating tractorbeam [XXXXX] on [Blabla Wreck][XXXX]"

<pre>Turret not fitted on shipID XXXXXXXXXXXXXXXXX</pre>

**Comment by Blafasl** [comment]
Yep, i get this, too. 

But this massage is only a follower of this: "Wrong object is trying to get turret attached due to wrong authored content! model:XXXXXXXXXXXXXXXXX bluetype:trinity.EveStation2"

Right before my Tengu wants to shoot stuff.

**Comment by pfruh** [comment]
I only have this one message and only on my Noctis, my Tengu is running without problems, just got 2 real exceptions on my tengu since the whole day and they sounded not really related to Questor.

**Comment by Blafasl** [comment]
I dont know exactly from where i comes, but its there in the logs and it happens when the ship comes out of the warp from an acceleration Gate in a mission. Also the six messages came in a timeframe of 2 seconds with 0,4s time between them.

Did you run an Guristas Extravaganza? I only ran this mission as my client throws away way too much exceptions because my questor wants to activate my shield booster twice sometimes.

Maybe its not actually coming from my ship but from the NPCs where the client wants to load an specific turret and fails. But i dont know. I post it here and maybe someone can do something with it.

**Comment by pfruh** [comment]
Yeah, i also ran Guristas Extravaganza, but disabled the LogServer and Salvaging as the LogServer tends to crash and fuck up my eve, so im just running missions right now as i havn't had any problems with them.

**Comment by Blafasl** [comment]
Okay, i'll try, i am just a bit over nervous when it comes to exceptions. Lets hope the best.

**Comment by pfruh** [comment]
For me, the problem happens in Object "FxSequencer" and Channel "scv-FxSequencer" so this might be just a problem with an effect of the new turret system.

**Comment by Blafasl** [comment]
i ran a bot for a quite few hours now. With your version it looks pretty good, the Log-Server throws much less exceptions than a few days ago and beside a innerspace instability it seems everything okay now. Lets hope CCP patches the turret problem and everything should be okay for now.
