### ISSUE TITLE
Transaction Data Delivery issue again

### ISSUE THREAD

**Issue by xelj** [Da-Teach/Questor#59]
Questor is not checked the mission before going to the agent. Pick-up station was lowsec, questor declined it after arriving to the agent and then again trying to get mission from storyline agent, agent says that there is no mission, and  questor stops.
## log:

 Questor: Random mission start delay of [0] seconds
 Questor: Storyline detected, doing storyline.
 Storyline: Going to do [Transaction Data Delivery] for agent [xxxxxx]
 TransactionDataDelivery: Switching to shuttle
 Traveler.StationDestination: Destination set to [xxxxxx]
 Traveler: Setting destination to [xxxxxx]
 Traveler: Warping to [Stargate (xxxxxx)]
 Traveler: Jumping to [xxxxxx]
 Traveler: Warping to [Stargate (xxxxxx)]
 Traveler: Jumping to [xxxxxx]
 Traveler.StationDestination: Warp to and dock at [xxxxxx]
 Traveler.StationDestination: Arrived in station
 AgentInteraction: Start conversation [Start Mission]
 AgentInteraction: Waiting for conversation
 AgentInteraction: Replying to agent
 AgentInteraction: Waiting for mission
 AgentInteraction: Faction fitting Default
 AgentInteraction: Declining low-sec mission
 AgentInteraction: Saying [Decline]
 AgentInteraction: Replying to agent

---

And after that questor stopped

**Comment by ISeeDEDPpl** [comment]
This is not an issue specific to that storyline. 
The problem seems to be that the same "decline" mechanism is being used for regular and storyline missions, but I don't think they use the same mechanism. 

Manually clicking "decline" has no effect for storyline missions from what I have seen. I had to manually right click the entry in the journal and choose the option to decline/remove from journal (not sure of the exact verbage)

I would imagine the most correct fix to be not to decline the mission at all, but to blacklist the agent like MaterialsForWarPreperation.cs does. 

```
            // No, black list the agent in this Questor session (note we will never decline storylines!)
            return StorylineState.BlacklistAgent;
```

Looking at storyline.cs It is unclear to me where to shoe horn it in...  AgentInteraction.cs or Storyline.cs likely...

My guess would be that this is rarely hit because questors  are mission'ing further from low sec.
